### ISSUE TITLE
Multiple functions

### ISSUE THREAD

**Issue by giany** [milancermak/lambda-pipeline#1]
First of all, nice work!

Secondly, any idea what is required to deploy multiple lambda functions? (creating multiple lambda*.yml for each function? what if each function has its own requirements.txt file?)

**Comment by milancermak** [comment]
This is a pain point I have as well and I'm afraid there is no good way to do this.

I'm replying with a slight delay because I had asked about this precise use case (having one pipeline deploy multiple functions) at the Ask an Architect session at AWS Summit I attended today. I wanted to hear what they have to say about it. I also [previously enquired](https://forums.aws.amazon.com/thread.jspa?threadID=253864) on the AWS forums.

As far as I can tell, there are two options here, none of them good:

1) Have multiple `AWS::Lambda::Function` resources in the `lambda.yml` (same solution as recommended in the forum post). That way, each one will be updated with a pipeline execution. The drawback here is that the deployment package (the output artifact of CodeBuild) is the same for all Lambdas. Basically, they differ only in the `Handler` property. All your dependencies across all of the functions must be specified in a single requirements.txt, so the functions will grow needlessly as you add dependencies, they have more exposure, the security is less tight, etc.

2) This is a solution the architect I talked to suggested. In the deploy phase of the pipeline, add an Invoke step which would take the CodeBuild artifact and split it manually to deployment packages and upload them to S3. Have the keys to these packages as input parameters for the CloudFormation update step. This solution of course defeats the whole purpose of an automated build-test-deploy pipeline...

I'm sorry to say I don't have a good solution. Sadly, the tooling around the whole Lambda ecosystem is still lacking. I hope AWS will improve it in the future though.

I hope I described it clearly enough. If you have any follow-up questions, feel free to ask.
